services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  producer:
    image: node:24.6.0-alpine3.22
    container_name: producer
    working_dir: /app
    volumes:
      - ./producer:/app
    command: sh -c "corepack enable && pnpm install --no-frozen-lockfile && node index.js"
    depends_on:
      - kafka

  consumer:
    image: node:24.6.0-alpine3.22
    container_name: consumer
    working_dir: /app
    volumes:
      - ./consumer:/app
    command: sh -c "corepack enable && pnpm install --no-frozen-lockfile && node index.js"
    depends_on:
      - kafka
